steps:
# ==============================================================================
# 1. Backend Build, Push, & Deploy
# ==============================================================================
  # Build Backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/arvion-repo/backend:latest'
      - './backend'
    id: 'Build Backend'

  # Push Backend Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/arvion-repo/backend:latest'
    id: 'Push Backend'

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'arvion-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/arvion-repo/backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--port'
      - '8080'
      - '--update-env-vars'
      - 'FIREBASE_PROJECT_ID=arvion-241094,FRONTEND_URL=https://arvion-frontend-348624065149.us-central1.run.app,PROLIXIS_BASE_URL=https://api.prolixis.ai/v1'
    id: 'Deploy Backend'

# ==============================================================================
# 2. Frontend Build, Push, & Deploy
# ==============================================================================
  # Build Frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://arvion-backend-348624065149.us-central1.run.app'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/arvion-repo/frontend:latest'
      - './frontend'
    id: 'Build Frontend'

  # Push Frontend Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/arvion-repo/frontend:latest'
    id: 'Push Frontend'

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'arvion-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/arvion-repo/frontend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--port'
      - '3000'
      # Ensuring the frontend has context of the live backend API
      - '--update-env-vars'
      - 'NEXT_PUBLIC_API_URL=https://arvion-backend-348624065149.us-central1.run.app'
    id: 'Deploy Frontend'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/arvion-repo/backend:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/arvion-repo/frontend:latest'


options:
  logging: CLOUD_LOGGING_ONLY
